### ISSUE TITLE
代码块超出部分被隐藏

### ISSUE THREAD

**Issue by caiyongmin** [uxcore/uxcore.github.com#9]
发现样式上 `overflow:hidden` 了，导致右边超出部分没有显示出来。
建议设成：`overflow-y: auto; overflow-x: hidden`。

![image](https://cloud.githubusercontent.com/assets/11053605/21419163/f4ac0610-c860-11e6-856b-ca365a62d7e1.png)

**Comment by eternalsky** [comment]
fix in https://github.com/uxcore/uxcore.github.com/commit/bbffba8b9656a374caad971facce9016e61dc49f
